# Generated by Django 4.0.3 on 2022-03-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Имя')),
                ('url', models.URLField(blank=True, null=True)),
                ('picture', models.CharField(blank=True, max_length=256, verbose_name='Изображение')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='Ширина')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Длина')),
                ('parent_picture', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
